services:
    mosquitto:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        container_name: mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ${SNAP_DATA}/docker-compose/ctrlx-docker-mosquitto-interface/config:/mosquitto/config
            - ${SNAP_DATA}/docker-volumes/ctrlx-docker-mosquitto-interface/data:/mosquitto/data
            - ${SNAP_DATA}/docker-volumes/ctrlx-docker-mosquitto-interface/log:/mosquitto/log
        restart: on-failure
